services:
  traefik:
    image: traefik:3.6.7
    container_name: traefik
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
      - ./traefik-plugin-authheader:/plugins-local/src/github.com/LittleAksMax/traefik-plugin-authheader
    env_file:
      - .env.shared.secret
      - .env.shared.config
      - .env.traefik
    command:
      - --configFile=/traefik.yml
    depends_on:
      - auth-service
    networks:
      - bids_backend
  policy-db:
    container_name: policy-db
    hostname: policy-db
    image: mongo:8.0-noble
    ports:
      - "27017:27017"
    env_file:
      - .env.policy-db
    restart: on-failure
    volumes:
      - ./policy_db/data:/data/db
      - ./policy_db/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - bids_backend
  auth-db:
    container_name: auth-db
    hostname: auth-db
    image: postgres:17
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env.auth-db
    volumes:
      - ./postgres/auth_db/data:/var/lib/postgresql/data
    networks:
      - bids_backend
  auth-service:
    build: ./auth-service
    hostname: auth-service
    container_name: auth-service
    env_file:
      - .env.auth-service.secret
      - .env.auth-service.config
      - .env.shared.secret
      - .env.shared.config
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - auth-db
    networks:
      - bids_backend
  policy-service:
    build: ./policy-service
    hostname: policy-service
    container_name: policy-service
    env_file:
      - .env.policy-service.secret
      - .env.policy-service.config
      - .env.shared.secret
      - .env.shared.config
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - policy-db
      - policy-cache
    networks:
      - bids_backend
  policy-cache:
    container_name: policy-cache
    image: redis:alpine3.20
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./redis/policy_cache/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/policy_cache/log:/var/opt/redislabs/log"
      - "./redis/policy_cache/data:/data"
    ports:
      - "6379:6379"
    networks:
      - bids_backend
  users-cache:
    container_name: users-cache
    image: redis:alpine3.20
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./redis/users_cache/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/users_cache/log:/var/opt/redislabs/log"
      - "./redis/users_cache/data:/data"
    ports:
      - "6380:6379"
    networks:
      - bids_backend
  users-db:
    container_name: users-db
    hostname: users-db
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.users-db
    volumes:
      - ./postgres/users_db/data:/var/lib/postgresql/data
    networks:
      - bids_backend
  user-service:
    build: ./user-service
    hostname: user-service
    container_name: user-service
    env_file:
      - .env.user-service.secret
      - .env.user-service.config
      - .env.shared.secret
      - .env.shared.config
    restart: unless-stopped
    ports:
      - "8083:8080"
    depends_on:
      - users-db
      - users-cache
    networks:
      - bids_backend
  bids-service:
    build: ./bids-service
    container_name: bids-service
    env_file:
      - .env.bids-service.secret
      - .env.bids-service.config
      - .env.shared.secret
      - .env.shared.config
    restart: unless-stopped
    depends_on:
      - user-service
      - policy-service
    networks:
      - bids_backend
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
      - "444:444"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - bids_frontend
      - bids_backend
  bidder-frontend:
    build: ./bidder-frontend
    container_name: bidder-frontend
    env_file:
      - .env.bidder-frontend
    restart: unless-stopped
    ports:
      - "81:81"
    depends_on:
      - user-service
      - policy-service
      - auth-service
      - traefik
    networks:
      - bids_frontend
networks:
  bids_backend:
    name: bids_backend
  bids_frontend:
    name: bids_frontend
