http:
  routers:
    users-router:
      rule: "Host(`localhost`) && (PathPrefix(`/user`) || PathPrefix(`/user/health`) || PathPrefix(`/lwa`))"
      service: users_service
      entryPoints:
        - websecure
      middlewares:
        - auth-header-transform
        - users-health-rewrite

  middlewares:
    users-health-rewrite:
      replacePathRegex:
        regex: "^/user/health$"
        replacement: "/health"

  services:
    users_service:
      loadBalancer:
        servers:
          # - url: "http://host.docker.internal:8083"
          - url: "http://user_service:8080"
